## Test workflow for aws creds retrieval
name: AWS Creds Grab
on:
  workflow_dispatch:
jobs:
  grab-creds:
    runs-on: ubuntu-latest
    permissions:
          contents: 'read'
          id-token: 'write'
    steps:
        - name: Configure Creds
          id: creds
          uses: aws-actions/configure-aws-credentials@v5.1.0
          with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::412381742094:role/GHA
            role-session-name: MySessionName
            output-credentials: true
        - name: Get Secret
          run: | 
                SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id here --query SecretString --output text)
                exch ${SECRET_VALUE}
          
    
      
            
