name: Test Script Checkout
on: 
  workflow_dispatch:
jobs:
    setup:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          id-token: write
      outputs:
        pyfiles: ${{steps.get-script.outputs.pyfiles}}
      steps:
        
        - name: Grab Script
          id: get-script
          uses: actions/checkout@v6
          with:
            repository: Annie-SW-QE/Learning-Actions
            ref: main
            sparse-checkout:
              palette_picker.py
              Palette_list.csv
              picker_requirements.txt
            sparse-checkout-cone-mode: false
        - name: show-me
          run: |
            echo "Files retrieved:"
            ls -1R | grep -v '^$' | grep -v ':$' || true
            echo "----"
          
        - name: Show sparse checkout file
          run: cat .git/info.sparse-checkout
          
        - name: Save file list as output
          id: files
          run: |
            PY_FILES=$(ls -1R | grep -v '^$' | grep -v ':$' | paste -sd "," -)
            echo "py_files=$PY_FILES" >> $GITHUB_OUTPUT
        - name: Show files as output
          run: |
            echo "Files from sparse checkout: ${{ steps.files.outputs.py_files }}"

          
