name: Test Script Checkout
on: 
  workflow_dispatch:
jobs:
    setup:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          id-token: write
      outputs:
        pyfiles: ${{steps.get-script.outputs.pyfiles}}
      steps:
        
        - name: Grab Script
          id: get-script
          uses: actions/checkout@v6
          with:
            repository: Annie-SW-QE/Learning-Actions
            ref: main
            sparse-checkout:
              palette_picker.py
              Palette_list.csv
              picker_requirements.txt
            sparse-checkout-cone-mode: false
        - name: show-capture
          id: files-saved
          run: |
              PY_FILES="$(git ls-files)"
              echo "Files retrieved:"
              echo "$PY_FILES"
              echo "py_files<<EOF" >> $GITHUB_OUTPUT
              echo "$PY_FILES" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
         

          
