name: Test Inputs
on:
 workflow_dispatch:
   inputs:
     name:
       description: 'Input to echo'
       required: true
       default: 'World'
     use-emoji:
       type: boolean
       description: 'Include emojis?'
jobs:
 greet:
   runs-on: ubuntu-latest
   steps:
     - name: Echo Input
       run: echo "${{ github.event.inputs.name }} ${{ fromJSON('[\"\", \"😊\"]')[github.event.inputs.use-emoji == 'true'] }}"
