name: Test Inputs
on:
 workflow_dispatch:
   inputs:
     name:
       description: 'Input to echo'
       required: true
       default: 'World'
   
jobs:
 greet:
   runs-on: ubuntu-latest
   steps:
     - name: Echo Input
       run: echo ${{github.event.inputs.name}}
