name: learn-workflows
on: 
  push:
    branches:
    - '**'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and echo new filename
        uses: actions/checkout@v5
        with: 
          fetch-depth: 2
      - name: Show filename
        run: echo $(git diff --name-only)
