name: learn-workflows
on: 
  push:
    branches:
    - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and echo new filename
        uses: actions/checkout@v5
        with: 
          fetch-depth: 2
      - name: Show filename
        
        run: echo $(git diff --name-only HEAD^)
      - name: Set filename
        run: echo "script_name=$(git diff --name-only HEAD^)}" >>"$GITHUB_OUTPUT"
      - name: Set up environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      
          

        
