name: Work Tasks
run-name: Work Task Test
on:
  push:
    branches:
      - 'workflow_test'
jobs:
   setup:
     runs-on: ubuntu-latest
     steps:
       ## checkout repo
       - name: Checkout repo and file types
         uses: actions/checkout@v5
         with:
           fetch-depth: 2
   #     ## store actor name as env for later use -- ${{github.triggering_actor}}
       - name: Get the last added file name
         run: echo $(git diff --name-only)
   #     ## check file types
   #     - name: Check file types and set up for language
   #       run: |
   #         changed_files = $(git diff --name-only HEAD^ HEAD)
   #         echo "Files changed in the latest push:"
   #         for file in $changed_files; do
   #           filename=$(basename "$file")
   #           extension="${filename##*.}"
   #           if [["$filename"== *>*]]; then
   #             echo "  - $file (Type: $extension)"
   #             if $extension == ".py"; then
   #               uses: actions/setup-python@v6
   #               with:
   #                   python-version: '3.13'
   #            else
   #              echo "  - $file (Type: No extension or directory)"
   #            fi
   #          done
   #      ## install dependencies
   #     - name: Install dependencies
   #       run: pip install -r requirements.txt
     
   # run-script:
   #      runs-on: windows-latest
   #      needs: setup
   #      steps:
   #      - name: run script
   #        run: python $filename
        
        ### run the script
  
   ## users who push to the branch will be notified by notifications settings being turned on for github actions
