name: python-script-manager
on:
  push:
    branches:
    - python-only
    
    paths-ignore:
      - ".github/workflows/**"
jobs:
  setup:

    runs-on: ubuntu-latest
    permissions:
          contents: 'read'
          id-token: 'write'
    outputs:
      pyfiles: ${{steps.file-list.outputs.pyfiles}}
      reqfiles: ${{steps.file-list.outputs.reqfiles}}
    steps:
      - name: Checkout and echo new filename
        uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Show filename

        run: echo $(git diff --name-only HEAD^)
      - name: Set file list
        id: file-list

        run: |
            if [[ "${{ github.event_name }}" == "push" ]]; then
            # For push events, compare against the previous commit in the branch
            changedfiles=$(git diff --name-only --diff-filter=AM "${{ github.event.before }}" "${{ github.sha }}")
            echo "$changedfiles"
            # YML_FILES=$(echo "$changedfiles" | grep '\.yml$')
            # echo "yaml_files=$YML_FILES" >> $GITHUB_OUTPUT
            PY_FILES=$(echo "$changedfiles" | grep '\.py$')
            echo "$PY_FILES"
            echo "pyfiles=$PY_FILES" >> $GITHUB_OUTPUT

            REQ_FILES=$(echo "$changedfiles" | grep '\.txt$')
            echo "reqfiles=$REQ_FILES" >> $GITHUB_OUTPUT

            fi




        # shell: bash


      - name: Check output
        run: |
              echo "The output is:${{steps.file-list.outputs.pyfiles}}"
              echo "The output is:${{steps.file-list.outputs.reqfiles}}"


  build:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
          contents: 'read'
          id-token: 'write'
    steps:
    - name: Setup Python

      uses: actions/setup-python@v6
      with:
            python-version: '3.13'
          # - name: Install dependencies
            ## grab requirements text from output

    - name: Echo Output
      id: get_file_name
      run: |
          echo "retrieved file is:${{needs.setup.outputs.pyfiles}}"
          echo "retrieved file is:${{needs.setup.outputs.reqfiles}}"
          echo "pyfilename=${{needs.setup.outputs.pyfiles}}" >> $GITHUB_OUTPUT
          echo "reqfilename=${{needs.setup.outputs.reqfiles}}" >> $GITHUB_OUTPUT
    - name: checkout again
      uses: actions/checkout@v5
      with:
          fetch-depth: 2
    - name: Install dependencies

      run: pip install -r ${{steps.get_file_name.outputs.reqfilename}}
    - name: Configure Creds
      id: creds
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::412381742094:role/GHA
            role-session-name: MySessionName
            output-env-credentials: true

    - name: Run script
      run: python ${{steps.get_file_name.outputs.filename}}
