#test passing vars to python script
name: Use Vars
on:
  workflow_dispatch:
jobs: 
    job1:
      runs-on: ubuntu-latest
      steps:
        # - uses: actions/checkout@v5
        - name: set var
          id: set-var
          
          run: | 
                 MY_VAR="woo"
                 echo "my_var=$MY_VAR >> $GITHUB_ENV
        - name: echo var
          run: echo ${{env.my_var}}
